name: main
on: 
  push: 
    branches:
      - main
jobs:
  build:
    runs-on : ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Chckout source code.
        uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci

      - name: General .env file
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
        env: 
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        
      - name: Build Production.
        run: npm run build --if-present

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy to S3
        env: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 sync --region ap-northeast-2 ./dist s3://triptrip-project --delete

      
